# Application
spring.application.name=laundry-locker-backend

# Server
server.port=8080

# DataSource - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/laundry_locker
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=laundry_locker_schema
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# i18n
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

# JWT
app.security.jwt.secret=Zk9Xc2Z3Y3dNVmN3M3d6dE1qVnRZbFJ4c2h0RkJ4Q0tQdXJqTnJZQQ==
app.security.jwt.expiration-ms=86400000
app.security.jwt.refresh-expiration-ms=2592000000

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

# Rate Limiting (disabled in dev for easier testing)
app.security.rate-limit.enabled=false
app.security.rate-limit.requests-per-minute=60

# Application Settings
app.name=Laundry Locker
app.frontend.url=http://localhost:3000
app.backend.url=http://localhost:8080

# Email Configuration (DEV - optional)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=baohuy2k12k4@gmail.com
spring.mail.password=xyifczlnwnpkwiyi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Email Expiration Settings
app.email.verification-expiration-ms=86400000
app.email.reset-password-expiration-ms=3600000
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# SQL + bind param
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Spring Security (JWT, Filter, AccessDenied, EntryPoint)
logging.level.org.springframework.security=DEBUG

# Filter chain (JwtAuthenticationFilter)
logging.level.org.springframework.web.filter=DEBUG

# Controller / Service / Security custom
logging.level.com.huynqb.springsecurity=DEBUG

# Exception handling (@ControllerAdvice)
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=DEBUG

# Error Response
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-exception=false
spring.web.error.include-stacktrace=never

# Logging settings
spring.output.ansi.enabled=ALWAYS
logging.level.root=INFO
logging.level.org.springframework=ERROR
logging.level.java.sql=INFO
logging.level.java.sql.Statement=DEBUG
logging.level.java.sql.PreparedStatement=DEBUG
logging.level.java.sql.ResultSet=DEBUG
logging.level.com.zaxxer.hikari=INFO

# OAuth2 Client - Google
spring.security.oauth2.client.registration.google.client-id=1027066205676-g9qiqugrfda7a0qblslutndcg4vi4njr.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# OAUTH2 CLIENT - GITHUB
spring.security.oauth2.client.registration.github.client-id=Ov23liIeOvLmTJL7URUe
spring.security.oauth2.client.registration.github.client-secret=470df5998715550bd7fc5222cfa8467937c2decc
spring.security.oauth2.client.registration.github.scope=user:email,read:user
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


# OAuth2 Client - Facebook
spring.security.oauth2.client.registration.facebook.client-id=1767424237196097
spring.security.oauth2.client.registration.facebook.client-secret=0483672ea068ffa668fac008f47caf8e
spring.security.oauth2.client.registration.facebook.scope=public_profile,email
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.facebook.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.facebook.client-authentication-method=client_secret_post

# OAuth2 Provider - Facebook
spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v18.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v18.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email,picture
spring.security.oauth2.client.provider.facebook.user-name-attribute=id


# OAuth2 Client - Zalo
spring.security.oauth2.client.registration.zalo.client-id=2955130960313894671
spring.security.oauth2.client.registration.zalo.client-secret=Vbb2ISZWEcYKJ3euT8km
spring.security.oauth2.client.registration.zalo.scope=profile
spring.security.oauth2.client.registration.zalo.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.zalo.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.zalo.client-authentication-method=client_secret_post


# OAuth2 Provider - Zalo
spring.security.oauth2.client.provider.zalo.authorization-uri=https://oauth.zaloapp.com/v4/authorize
spring.security.oauth2.client.provider.zalo.token-uri=https://oauth.zaloapp.com/v4/access_token
spring.security.oauth2.client.provider.zalo.user-info-uri=https://graph.zalo.me/v2.0/me?fields=id,name,picture
spring.security.oauth2.client.provider.zalo.user-name-attribute=id



